
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GoogleSearch.Models
{

    using System;
    using System.Collections.Generic;

    public partial class SearchSummery
    {

        public int Id { get; set; }

        public string SearchTerm { get; set; }

        public System.DateTime SearchTime { get; set; }

        public int ResultCount { get; set; }

        public System.TimeSpan Duration { get; set; }

    }

}
